import * as T from './vendor/three.module.js';
import {panelTarget} from './vr-pointer.js';
export class ActionMenu {
 constructor(scene,onMessage){this.onMessage=onMessage;this.canvas=document.createElement('canvas');this.canvas.width=900;this.canvas.height=1100;this.texture=new T.CanvasTexture(this.canvas);this.texture.colorSpace=T.SRGBColorSpace;this.mesh=new T.Mesh(new T.PlaneGeometry(.78,.95),new T.MeshBasicMaterial({map:this.texture,side:T.DoubleSide,transparent:true,depthTest:false,depthWrite:false,toneMapped:false}));this.mesh.renderOrder=100.5;this.mesh.visible=false;scene.add(this.mesh);this.element=document.createElement('section');this.element.id='actionMenu';this.element.hidden=true;this.element.setAttribute('aria-label','Object and person actions');document.body.append(this.element);this.hovered=new Set();this.buttons=[];this.open=false;}
 show({title,subtitle='',anchor,options}){this.title=title;this.subtitle=subtitle;this.anchor=anchor;this.options=[...options,{id:'close',label:'Close',run:()=>{}}];this.open=true;this.hovered.clear();this.element.replaceChildren();const heading=document.createElement('b');heading.textContent=title;this.element.append(heading);const small=document.createElement('small');small.textContent=subtitle;this.element.append(small);const list=document.createElement('div');list.className='action-options';this.options.forEach((o,i)=>{const b=document.createElement('button');b.dataset.action=o.id||String(i);b.textContent=o.label;b.setAttribute('aria-disabled',String(!!o.disabled));if(o.disabled){const reason=document.createElement('small');reason.textContent=o.reason;b.append(reason);}b.onclick=()=>this.activate(i);list.append(b);});this.element.append(list);this.draw();}
 hide(){this.open=false;this.mesh.visible=false;this.element.hidden=true;this.hovered.clear();}
 activate(i){const o=this.options[i];if(!o)return;if(o.disabled){this.onMessage(o.reason||'This action is unavailable.');return;}this.hide();o.run();}
 draw(){const x=this.canvas.getContext('2d');x.clearRect(0,0,900,1100);x.fillStyle='#163b42';x.beginPath();x.roundRect(0,0,900,1100,28);x.fill();x.fillStyle='#f3d290';x.font='bold 35px sans-serif';x.fillText(this.title.slice(0,40),30,58);x.fillStyle='#c6ddd2';x.font='22px sans-serif';x.fillText(this.subtitle.slice(0,63),30,97);this.buttons=[];this.options.forEach((o,i)=>{const bx=25+i%2*440,by=130+Math.floor(i/2)*120;this.buttons.push({x:bx,y:by,w:415,h:105,action:()=>this.activate(i)});x.fillStyle=this.hovered.has(i)?'#397f79':o.disabled?'#293f45':'#315961';x.beginPath();x.roundRect(bx,by,415,105,12);x.fill();x.fillStyle=o.disabled?'#8caaa4':'#f5f5e7';x.font='24px sans-serif';x.fillText(o.label.slice(0,30),bx+13,by+42);if(o.disabled){x.font='18px sans-serif';x.fillText((o.reason||'Locked').slice(0,38),bx+13,by+77);}if(this.hovered.has(i)){x.strokeStyle='#96ffe5';x.lineWidth=4;x.stroke();}});this.texture.needsUpdate=true;}
 setHover(indices){if([...indices].join(',')!==[...this.hovered].join(',')){this.hovered=indices;this.draw();}}
 target(ray,c){return panelTarget(ray,c,this.mesh,this.buttons,900,1100);}
 update(camera,isVR){if(!this.open)return;const point=this.anchor();if(!point){this.hide();return;}this.element.hidden=isVR;this.mesh.visible=isVR;if(isVR){const eye=camera.getWorldPosition(new T.Vector3());this.mesh.position.copy(point);this.mesh.position.y+=.5;this.mesh.quaternion.copy(camera.getWorldQuaternion(new T.Quaternion()));const d=eye.distanceTo(this.mesh.position);this.mesh.scale.setScalar(T.MathUtils.clamp(d*.48,.65,1.3));}else{const screen=point.clone().project(camera);const x=(screen.x+1)*innerWidth/2,y=(1-screen.y)*innerHeight/2;const width=Math.min(360,innerWidth-24);this.element.style.width=width+'px';this.element.style.left=T.MathUtils.clamp(x-width/2,12,innerWidth-width-12)+'px';const h=this.element.offsetHeight;this.element.style.top=T.MathUtils.clamp(y-h-12,82,Math.max(82,innerHeight-h-82))+'px';}}
}
