import test from 'node:test';import assert from 'node:assert/strict';import * as T from '../vendor/three.module.js';
import {moveVector,stickAxes} from '../controls.js';import {SOCIAL,objectActions} from '../actions.js';
import {household,person,edge,approach,order,tick,relationship,rotateObject,socialReason,cancelAction,upgradeState} from '../sim.js';
const q=yaw=>new T.Quaternion().setFromAxisAngle(new T.Vector3(0,1,0),yaw);
const near=(a,b)=>assert.ok(a.distanceTo(b)<1e-6,`${a.toArray()} != ${b.toArray()}`);
test('forward stays relative to the headset with rig turns and correct Quest stick axes',()=>{near(moveVector(0,-1,q(0),q(0),1),new T.Vector3(0,0,-1));near(moveVector(0,-1,q(Math.PI/2),q(0),1),new T.Vector3(-1,0,0));near(moveVector(0,-1,q(Math.PI/2),q(Math.PI/2),1),new T.Vector3(0,0,1));near(moveVector(1,0,q(0),q(0),1),new T.Vector3(1,0,0));assert.deepEqual(stickAxes({gamepad:{axes:[.9,.8,.25,-1]}}),[.25,-1]);assert.ok(Math.abs(moveVector(1,-1,q(0),q(0),1).length()-1)<1e-6);});
test('stoves can only be used from an unobstructed front without reaching through walls',()=>{const s=household(2),p=s.people[0];p.x=0;p.z=3;const o={id:1,type:'stove',x:0,z:0,rot:0};s.objects=[o];assert.deepEqual(approach(s,p,o).at(-1),[0,-1]);s.walls[edge(0,0,1)]='wall';assert.equal(approach(s,p,o),null);assert.equal(order(s,p,{kind:'object',id:1}),false);assert.ok(rotateObject(s,1));assert.deepEqual(approach(s,p,o).at(-1),[-1,0]);s.objects.push({id:2,type:'counter',x:-1,z:0,rot:0});assert.equal(approach(s,p,o),null);});
test('rotation changes placed furniture and rejects an overlapping footprint',()=>{const s=household(2);s.people[0].z=5;s.objects=[{id:1,type:'bed',x:0,z:0,rot:0},{id:2,type:'chair',x:1,z:0,rot:0}];assert.equal(rotateObject(s,1),false);assert.equal(s.objects[0].rot,0);s.objects.pop();assert.ok(rotateObject(s,1));assert.equal(s.objects[0].rot,1);});
function complete(s,p){for(let i=0;i<2000&&p.task;i++)tick(s,.5,false);assert.equal(p.task,null);}
test('friendship unlocks romance, engagement, marriage, private time and a later child',()=>{const s=household(2),p=s.people[0],other=person('Mira',1,4,'#bd7965',{gender:'female'});s.people.push(other);s.objects.push({id:1,type:'doublebed',x:0,z:1,rot:0});assert.match(socialReason(s,p,other,'kiss'),/Friendship/);for(let i=0;i<9;i++){assert.ok(order(s,p,{kind:'social',id:other.id,action:'talk'}));complete(s,p);}for(let i=0;i<5;i++){assert.ok(order(s,p,{kind:'social',id:other.id,action:'flirt'}));complete(s,p);}for(const action of ['kiss','propose','marry','tryBaby']){assert.equal(socialReason(s,p,other,action),null,action);assert.ok(order(s,p,{kind:'social',id:other.id,action}),action);complete(s,p);}assert.equal(relationship(s,p,other).status,'married');assert.equal(p.spouse,other.id);assert.ok(other.pregnancy);s.day=other.pregnancy.dueDay;tick(s,.1,false);assert.equal(s.people.length,3);assert.deepEqual(new Set(s.people[2].parents),new Set([p.id,other.id]));assert.equal(s.people[2].generation,2);});
test('romance is unavailable for children or relatives and cancellation grants no relationship reward',()=>{const s=household(),[p,other]=s.people;other.ageYears=12;assert.match(socialReason(s,p,other,'flirt'),/adults/);other.ageYears=25;other.parents=[p.id];assert.match(socialReason(s,p,other,'flirt'),/adults/);other.parents=[];assert.ok(order(s,p,{kind:'social',id:other.id,action:'talk'}));cancelAction(p);tick(s,1,false);assert.equal(relationship(s,p,other).friendship,0);assert.equal(other.heldBy,null);});
test('every furnishing has more than one usable menu choice and naps are shorter',()=>{for(const o of household().objects)assert.ok(objectActions(o.type).length>=2,o.type);const s=household(),p=s.people[0],o=s.objects.find(o=>o.type==='bed');assert.ok(order(s,p,{kind:'object',id:o.id,action:'nap'}));assert.equal(p.task.stages[1].duration,22);assert.equal(order(s,p,{kind:'object',id:o.id,action:'not-a-real-action'}),false);});

test('older saves cancel routines that may have started on an invalid side of furniture',()=>{const s=household(),p=s.people[0];p.task={kind:'object',phase:'cook',stages:[{kind:'cook'}],index:0};delete s.interactionVersion;upgradeState(s);assert.equal(p.task,null);assert.equal(s.interactionVersion,1);});
