import test from 'node:test';import assert from 'node:assert/strict';
import {household,order,tick,activeStage,footprint,blocked,welcomeChild,advanceAges,upgradeState,lifeStage,cancelAction} from '../sim.js';
import {createHuman,animateHuman,makeFurniture} from '../living-art.js';
import * as T from '../vendor/three.module.js';
function runUntil(s,p,phase){for(let i=0;i<2400;i++){if(p.task?.phase===phase)return;tick(s,.5,false);}assert.fail('Never reached '+phase);}
test('a meal goes through ingredients, preparation, cooking, seated eating and dishwashing',()=>{const s=household(),p=s.people[0];p.needs.Hunger=20;assert.ok(order(s,p,{kind:'object',id:s.objects.find(o=>o.type==='fridge').id}));assert.deepEqual(p.task.stages.map(q=>q.kind),['retrieve','prepare','cook','sit','eat','stand','loadDishwasher']);runUntil(s,p,'cook');assert.ok(p.needs.Hunger<20,'cooking alone must not fill hunger');runUntil(s,p,'eat');assert.ok(activeStage(p).seated);const h=p.needs.Hunger;tick(s,2,false);assert.ok(p.needs.Hunger>h);runUntil(s,p,'loadDishwasher');assert.ok(p.needs.Hunger>60);for(let i=0;i<30;i++)tick(s,.5,false);assert.equal(p.task,null);});
test('appliances are reserved and deleted destinations interrupt a routine',()=>{const s=household(),[p,q]=s.people,fridge=s.objects.find(o=>o.type==='fridge');assert.ok(order(s,p,{kind:'object',id:fridge.id}));assert.equal(order(s,q,{kind:'object',id:fridge.id}),false);runUntil(s,p,'cook');s.objects=s.objects.filter(o=>o.type!=='chair');for(let i=0;i<100;i++)tick(s,.5,false);assert.equal(p.task,null);cancelAction(p);assert.ok(order(s,q,{kind:'object',id:fridge.id}));});
test('sleep and swim include entry and exit stages with real poses',()=>{for(const [type,phases]of [['bed',['getInBed','sleep','getOutBed']],['pool',['enterPool','swim','exitPool']]]){const s=household(),p=s.people[0];assert.ok(order(s,p,{kind:'object',id:s.objects.find(o=>o.type===type).id}));assert.deepEqual(p.task.stages.map(st=>st.kind),phases);runUntil(s,p,phases[1]);const g=createHuman(p);animateHuman(g,p,s,3);assert.ok(Math.abs(g.rotation.x)>1);runUntil(s,p,phases[2]);}});
test('car arrives, boards, departs, returns, pays once, and drives away',()=>{const s=household(),p=s.people[0],money=s.money,seen=new Set();assert.ok(order(s,p,{kind:'work'}));for(let i=0;i<1500;i++){seen.add(s.car.phase);tick(s,.5,false);}for(const phase of ['arriving','parked','boarding','departing','away','returning','alighting','leaving','idle'])assert.ok(seen.has(phase),phase);assert.equal(s.money,money+450);assert.equal(p.job,0);assert.equal(s.car.phase,'idle');});
test('legacy households migrate and descendants inherit identity across generations',()=>{const s=household();delete s.livingVersion;delete s.car;delete s.people[0].ageYears;upgradeState(s);assert.equal(s.people[0].ageYears,27);const child=welcomeChild(s,s.people[0].id);assert.equal(child.generation,2);assert.equal(child.skin,s.people[0].skin);assert.equal(child.parents.length,2);s.aging=false;advanceAges(s);assert.equal(child.ageYears,1);s.aging=true;for(let i=0;i<17;i++)advanceAges(s);assert.equal(lifeStage(child),'Adult');const next=welcomeChild(s,child.id);assert.equal(next.generation,3);const restored=upgradeState(JSON.parse(JSON.stringify(s)));assert.equal(restored.people.at(-1).parents[0],child.id);});
test('rotated long beds and pools occupy all their cells',()=>{const s=household(2);s.objects=[{id:1,type:'bed',x:0,z:0,rot:1}];assert.deepEqual(footprint(s.objects[0]),[[0,0],[1,0]]);assert.ok(blocked(s,1,0));assert.equal(footprint({type:'pool',x:0,z:0,rot:1}).length,4);});
test('human skinning preserves face geometry and animated joints',()=>{const s=household(),p=s.people[0],g=createHuman(p),body=g.children.find(c=>c.isSkinnedMesh);g.updateMatrixWorld(true);body.skeleton.update();assert.ok(body.geometry.attributes.position.count>10000);assert.ok(body.skeleton.bones.length>=13);const pos=body.geometry.attributes.position,v=new T.Vector3();for(let i=0;i<pos.count;i+=107){v.fromBufferAttribute(pos,i);const expected=v.clone();body.applyBoneTransform(i,v);assert.ok(v.distanceTo(expected)<.00001,'bind pose changed geometry');}p.path=[[p.x+1,p.z]];animateHuman(g,p,s,1);assert.notEqual(g.userData.parts.thighL.rotation.x,0);const child=createHuman({...p,ageYears:9});assert.ok(child.scale.x<g.scale.x);});
