import test from 'node:test';
import assert from 'node:assert/strict';
import * as T from '../vendor/three.module.js';
import {panelTarget,createControllerPointer} from '../vr-pointer.js';
const buttons=[{x:35,y:315,w:405,h:70},{x:460,y:315,w:405,h:70}];
function fixture(){const scene=new T.Scene(),rig=new T.Group(),c=new T.Group(),panel=new T.Mesh(new T.PlaneGeometry(.9,1.1),new T.MeshBasicMaterial({side:T.DoubleSide}));scene.add(rig,panel);rig.add(c);panel.position.set(0,1.5,-1.4);return {scene,rig,c,panel,ray:new T.Raycaster()};}
function aim(f,x,y){f.panel.updateWorldMatrix(true,false);const point=f.panel.localToWorld(new T.Vector3((x/900-.5)*.9,(.5-y/1100)*1.1,0));f.c.updateWorldMatrix(true,false);const origin=f.c.getWorldPosition(new T.Vector3());const q=new T.Quaternion().setFromRotationMatrix(new T.Matrix4().lookAt(origin,point,new T.Vector3(0,1,0)));const parent=f.c.parent.getWorldQuaternion(new T.Quaternion()).invert();f.c.quaternion.copy(parent.multiply(q));return point;}
const hit=f=>panelTarget(f.ray,f.c,f.panel,buttons,900,1100);
test('ray targets the same button before and at trigger selection',()=>{const f=fixture();f.c.position.set(.2,1.2,0);aim(f,650,350);assert.equal(hit(f).buttonIndex,1);assert.strictEqual(hit(f).button,buttons[1]);});
test('moved panel and translated/turned rig use fresh world matrices',()=>{const f=fixture();f.rig.position.set(2,0,1);f.rig.rotation.y=.6;f.c.position.set(.2,1.2,0);f.panel.position.set(1,1.5,-1);f.panel.rotation.y=.4;aim(f,200,350);assert.equal(hit(f).buttonIndex,0);f.panel.position.x+=.7;f.panel.rotation.y=-.2;aim(f,650,350);assert.equal(hit(f).buttonIndex,1);});
test('panel gaps, off-panel rays, and hidden panel do not select buttons',()=>{const f=fixture();f.c.position.y=1.3;aim(f,445,350);assert.ok(hit(f).hit);assert.equal(hit(f).buttonIndex,-1);aim(f,1000,350);assert.equal(hit(f).hit,null);aim(f,650,350);f.panel.visible=false;assert.equal(hit(f).hit,null);});
test('beam endpoint and cursor coincide with panel intersection and render above it',()=>{const f=fixture();f.c.position.set(.2,1.2,0);aim(f,650,350);const target=hit(f),p=createControllerPointer(f.c,f.scene);f.panel.renderOrder=100;p.update(target.hit,f.panel,true);p.beam.updateWorldMatrix(true,false);const end=p.beam.localToWorld(new T.Vector3(0,0,-1));assert.ok(end.distanceTo(target.hit.point)<1e-6);assert.ok(p.cursor.position.distanceTo(end)<1e-6);assert.ok(p.beam.renderOrder>f.panel.renderOrder);assert.equal(p.beam.material.depthTest,false);assert.equal(p.beam.material.depthWrite,false);assert.ok(p.cursor.children.every(m=>m.renderOrder>f.panel.renderOrder&&!m.material.depthTest));p.hide();assert.equal(p.beam.visible,false);assert.equal(p.cursor.visible,false);});
test('two controllers retain independent cursors and tracking loss hides feedback',()=>{const f=fixture(),other=new T.Group();f.rig.add(other);f.c.position.set(.2,1.2,0);other.position.set(-.2,1.2,0);const a=createControllerPointer(f.c,f.scene),b=createControllerPointer(other,f.scene);aim(f,650,350);a.update(hit(f).hit,f.panel,true);aim({...f,c:other},200,350);b.update(hit({...f,c:other}).hit,f.panel,true);assert.notDeepEqual(a.cursor.position.toArray(),b.cursor.position.toArray());f.c.visible=false;a.update(hit(f).hit,f.panel,false);assert.equal(a.cursor.visible,false);assert.equal(a.beam.visible,false);assert.equal(b.cursor.visible,true);});
